name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build:
    name: Build
    runs-on: macos-latest
    strategy:
      matrix:
        go:
          - '1.23'

    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Test code
      run: go test -v ./...

    - name: Create package
      run: make

    - name: Archive generated package
      uses: actions/upload-artifact@v4
      with:
        name: alfred-unixtime-converter
        path: UnixtimeConverter.alfredworkflow
